import miniManualSatker from "./imgs/mini-manual-staker.jpeg"
import batteryOperatedTruk from "./imgs/image (5).png"

export let itmes =[
    {
    Image:miniManualSatker,
    Name:"Mini Manual Stacker",
    Application: "Industrial",
    Color: "Yellow",
    Capacity: "1-3tons",
    DrivenType: "Hydraulic",
    Warranty: "1 Year",
    Type:"",
    Power:"",
    Voltage:"",
    Certification:"",
    Material: "",
    Shape: "",
    Style: "Flat",
},
{
    Image:batteryOperatedTruk,
    Name:"Battery Operated Pallet Truck",
    Application: "Industrial",
    Color: "Yellow",
    Capacity: "",
    DrivenType: "Battery Operated",
    Warranty: "1 Year",
    Certification: "CE Certified",
    Type:"",
    Power:"",
    Voltage:"",
    Material: "",
    Shape: "",
    Style: "",
},{
    Image:miniManualSatker,
    Name:"Winch Goods Lift",
    Application: "Industrial",
    Color: "Yellow",
    Capacity: "1-3tons",
    DrivenType: "Hydraulic",
    Warranty: "1 Year",
    Type:"Automatic",
    Voltage:"380V",
    Power:'1-3kw',
    Material: "",
    Shape: "",
    Style: "",
    Certification:''
},{
    Image:miniManualSatker,
    Name:"Utility Pallet Trolley",
    Application: "Industrial",
    Color: "Grey",
    Capacity: "200-300kg",
    DrivenType: "Hydraulic",
    Warranty: "1 Year",
    Type: "Portable",
    Material: "Iron, Steel",
    Shape: "Rectangular",
    Style: "Flat",
    Voltage:"",
    Power:'',
    Certification:""
},{
    Image:miniManualSatker,
    Name:"Foldable Platform Trolley",
    Application: "Industrial",
    Color: "Yellow",
    Capacity: "1-3tons",
    DrivenType: "Hydraulic",
    Warranty: "1 Year",
    Type: "Foldable",
    Material: "Stainless Steel",
    Shape: "",
    Style: "",
    Voltage:"",
    Power:'',
    Certification:""
},{
    Image:miniManualSatker,
    Name:"Mobile Dock Leveller",
    Color: "Yellow",
    DrivenType:"",
    Capacity: "9-6tons",
    Warranty: "1 Year",
    Type: "Hydraulic",
    Application: "Lifting Heavy Loads",
    Material: "Mild Steel",
    Shape: "",
    Style: "",
    Voltage:"",
    Power:'',
    Certification:""
},
{
    Image:miniManualSatker,
    Name:"Hydraulic Scissor Lift",
    Application: "Industrial",
    Capacity: "200-300kg",
    DrivenType: "Hydraulic",
    Warranty: "1 Year",
    Type: "Hydraulic",
    Material: "Iron, Steel",
    Shape: "Rectangular",
    Style: "Flat",
    Color: "Grey",
    Voltage:"",
    Power:'',
    Certification:""
},{
    Image:miniManualSatker,
    Name:"Hydraulic Dock Leveler",
    Application: "Dock Use",
    Color: "Grey",
    Capacity: "200-300kg",
    DrivenType: "Hydraulic",
    Warranty: "1 Year",
    Type: "Portable Semi Automatic",
    Material: "Iron, Steel",
    Shape: "Rectangular",
    Style: "Flat",
    Finishing: "Polished",
    Voltage:"",
    Power:'',
    Certification:""
}]

export let product =[
    {categoryItems:itmes,
    categorieName:"Industrial Stackers"},
    {categoryItems:itmes,
        categorieName:"Pallet Trucks"},
    {categoryItems:itmes,
        categorieName:"Pallet Trolleys"},
    {categoryItems:itmes,
        categorieName:"Platform Trolleys"},
    {categoryItems:itmes,
        categorieName:"Goods Lifts"},
    {categoryItems:itmes,
        categorieName:"Scissor Lifts"},
    {categoryItems:itmes,
        categorieName:"Floor Cranes"},
    {categoryItems:itmes,
        categorieName:"Other Products"},
]